runtime: nodejs20

env_variables:
  NODE_ENV: production

handlers:
  - url: /(.*\.(js|css|ico|png|jpg|jpeg|gif|svg|webp|woff|woff2|ttf|eot))$
    static_files: dist/\1
    upload: dist/(.*\.(js|css|ico|png|jpg|jpeg|gif|svg|webp|woff|woff2|ttf|eot))$
    secure: always
    http_headers:
      Cache-Control: "public, max-age=31536000"

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
    http_headers:
      Cache-Control: "no-cache, no-store, must-revalidate"

skip_files:
  - ^(?!.*dist).*$
  - ^dist/(?!.*\.(js|css|html|ico|png|jpg|jpeg|gif|svg|webp|woff|woff2|ttf|eot)$).*$

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6