// Lightweight AI provider factory stub for admin panel
// Keeps build working even if real AI providers aren’t configured.

export type AdminAIProvider = 'gemini' | 'openai' | 'perplexity';

interface GenerateContentOptions {
  topic: string;
  contentType?: string;
  tone?: string;
  targetWordCount?: number;
  keywords?: string[];
  generateOutlineFirst?: boolean;
  category?: string | undefined;
}

export const aiFactory = {
  async generateContent(
    options: GenerateContentOptions,
    provider: AdminAIProvider = 'gemini'
  ) {
    const wordCount = options.targetWordCount ?? 1500;

    return {
      title: options.topic || 'AI Generated Title',
      content:
        'This is placeholder AI-generated content. Configure real AI providers to get production content.',
      excerpt:
        'Placeholder excerpt generated by the admin AI stub. Replace with real AI output in production.',
      metaTitle: options.topic || 'AI Generated Meta Title',
      metaDescription:
        'Placeholder meta description generated by the admin AI stub. Update once AI providers are configured.',
      keywords: options.keywords ?? [],
      outline: [],
      readingTime: Math.max(1, Math.round(wordCount / 200)),
      provider,
    } as const;
  },
};

export default aiFactory;
